### PR TITLE
prevent normal user from visiting non-congregation pages

### PR DESCRIPTION
**Pull request by benscriptstheweb**
for now the changes are on the following vue files:
- CongregationForm
- Masthead
- Territories
- Territory

### CODE REVIEW

**Comment by rtercias** [comment]
Is this ready to be reviewed and merged?

**Comment by benscriptstheweb** [comment]
> Is this ready to be reviewed and merged?

yes, i think so.

**Comment by rtercias** [comment]
I did a test drive. It mostly works well. One thing though, in the Territory page, when the territory's congregation doesn't match, can you also reset the selected group id to zero? Without this, when the user tries to go back to the Territories page, they are perpetually redirected to the unauthorized page, due to the previously selected unauthorized territory (we're setting the current group based on that territory).

**Comment by rtercias** [comment]
further testing shows that these routes also need to be limited: 
http://localhost:8080/territories/53/addresses/5000/detail?origin=phone
http://localhost:8080/territories/53/addresses/5000/edit?origin=phone
http://localhost:8080/reports/assignment-report/7
http://localhost:8080/reports/dnc/1

this one, i'm not sure, but it looks like it's getting the cong id from the user object:
http://localhost:8080/reports/logs/addresses?fullscreen=true

if so, then this last one is ok.

You may need to give yourself Terr Servant privilege to see some of these pages if you don't already have that.

**Comment by benscriptstheweb** [comment]
hmm... are these routes valid?

"../territories/53" is elmwood park for me. when i click the back route from ../territories/53/addresses/5000/ it then takes me to ./territories/253. but when i do ./territories/253/addresses/5000, it gives me the Unauthorized page.

**Comment by benscriptstheweb** [comment]
> further testing shows that these routes also need to be limited: http://localhost:8080/territories/53/addresses/5000/detail?origin=phone http://localhost:8080/territories/53/addresses/5000/edit?origin=phone http://localhost:8080/reports/assignment-report/7 http://localhost:8080/reports/dnc/1
> 
> this one, i'm not sure, but it looks like it's getting the cong id from the user object: http://localhost:8080/reports/logs/addresses?fullscreen=true
> 
> if so, then this last one is ok.
> 
> You may need to give yourself Terr Servant privilege to see some of these pages if you don't already have that.

Okay, I can get started on these.

**Review by rtercias — APPROVED** [review]
Approved... but needs a rebase to get latest from master.

**Comment by benscriptstheweb** [comment]
Hi Kuya, I will move a cleaner version of this 'adventure' to a new upstreamed branch 😄

**Pull request closed without merging**
